/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ZMK_IPC_ZMK_IPC_PB_H_INCLUDED
#define PB_ZMK_IPC_ZMK_IPC_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* HID transport over which a report was sent. */
typedef enum _zmk_ipc_TransportType {
    zmk_ipc_TransportType_TRANSPORT_UNSPECIFIED = 0,
    /* No transport is active (keyboard not connected). */
    zmk_ipc_TransportType_TRANSPORT_NONE = 1,
    /* USB HID. */
    zmk_ipc_TransportType_TRANSPORT_USB = 2,
    /* Bluetooth HID over GATT (HOG). */
    zmk_ipc_TransportType_TRANSPORT_BLE = 3
} zmk_ipc_TransportType;

/* Whether this is a press or a release. */
typedef enum _zmk_ipc_KeyEvent_Action {
    zmk_ipc_KeyEvent_Action_ACTION_UNSPECIFIED = 0,
    zmk_ipc_KeyEvent_Action_PRESS = 1,
    zmk_ipc_KeyEvent_Action_RELEASE = 2
} zmk_ipc_KeyEvent_Action;

/* Struct definitions */
/* Identifies the specific endpoint (transport + optional BLE profile). */
typedef struct _zmk_ipc_Endpoint {
    zmk_ipc_TransportType transport;
    /* BLE profile index (0-based). Meaningful only when
 transport == TRANSPORT_BLE. */
    uint32_t ble_profile_idx;
} zmk_ipc_Endpoint;

/* Position in the logical key matrix. */
typedef struct _zmk_ipc_KeyPosition {
    uint32_t row;
    uint32_t col;
} zmk_ipc_KeyPosition;

/* A key press or release event. */
typedef struct _zmk_ipc_KeyEvent {
    zmk_ipc_KeyEvent_Action action;
    pb_size_t which_address;
    union {
        zmk_ipc_KeyPosition key_pos;
        uint32_t position;
    } address;
} zmk_ipc_KeyEvent;

/* Top-level wrapper for all client → ZMK messages.
 Extend with additional variants (e.g. reset, layer control) as needed. */
typedef struct _zmk_ipc_ClientMessage {
    pb_size_t which_payload;
    union {
        zmk_ipc_KeyEvent key_event;
    } payload;
} zmk_ipc_ClientMessage;

/* Raw key matrix event from the kscan subsystem.
 Corresponds to zmk_position_state_changed in ZMK's event system.
 Fired before keymap processing (before any hold-tap / combo logic). */
typedef struct _zmk_ipc_KscanEvent {
    /* Source identifier.
 ZMK_POSITION_STATE_CHANGE_SOURCE_LOCAL == 255 means the local MCU. */
    uint32_t source;
    /* Linear position in the key matrix (row * columns + col). */
    uint32_t position;
    /* true = key pressed, false = key released. */
    bool pressed;
    /* Kernel uptime at event time, milliseconds. */
    int64_t timestamp;
} zmk_ipc_KscanEvent;

typedef PB_BYTES_ARRAY_T(32) zmk_ipc_HidKeyboardReport_keys_t;
/* HID keyboard report sent to a transport endpoint.
 Fired after keymap + modifier processing, immediately before the report
 is written to USB / BLE.

 Modifier byte bit layout (USB HID spec, page 59):
   bit 0 – Left Ctrl    bit 4 – Right Ctrl
   bit 1 – Left Shift   bit 5 – Right Shift
   bit 2 – Left Alt     bit 6 – Right Alt
   bit 3 – Left GUI     bit 7 – Right GUI

 keys byte layout:
   HKRO mode: 6 bytes, each a HID usage ID (0 = not pressed)
   NKRO mode: bitmap of all supported HID usage IDs */
typedef struct _zmk_ipc_HidKeyboardReport {
    bool has_endpoint;
    zmk_ipc_Endpoint endpoint;
    uint32_t modifiers;
    /* Raw key bytes — length depends on HKRO / NKRO build configuration. */
    zmk_ipc_HidKeyboardReport_keys_t keys;
} zmk_ipc_HidKeyboardReport;

typedef PB_BYTES_ARRAY_T(16) zmk_ipc_HidConsumerReport_keys_t;
/* HID consumer (media key) report sent to a transport endpoint.

 keys byte layout:
   BASIC mode (CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC):
     N × uint8  (one usage ID per slot, up to 0xFF)
   FULL mode (CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_FULL):
     N × uint16 little-endian (one usage ID per slot, up to 0xFFF)
   N = CONFIG_ZMK_HID_CONSUMER_REPORT_SIZE (default 6) */
typedef struct _zmk_ipc_HidConsumerReport {
    bool has_endpoint;
    zmk_ipc_Endpoint endpoint;
    /* Raw key bytes — interpret according to consumer report mode above. */
    zmk_ipc_HidConsumerReport_keys_t keys;
} zmk_ipc_HidConsumerReport;

/* HID mouse / pointing report sent to a transport endpoint.
 Only present when CONFIG_ZMK_POINTING is enabled. */
typedef struct _zmk_ipc_HidMouseReport {
    bool has_endpoint;
    zmk_ipc_Endpoint endpoint;
    /* Button bitmask (bit N = button N+1 pressed). */
    uint32_t buttons;
    /* Pointer displacement since last report (HID resolution units). */
    int32_t dx;
    int32_t dy;
    /* Scroll wheel displacement. */
    int32_t scroll_x;
    int32_t scroll_y;
} zmk_ipc_HidMouseReport;

/* Top-level wrapper for all ZMK → client notifications. */
typedef struct _zmk_ipc_ZmkEvent {
    pb_size_t which_payload;
    union {
        zmk_ipc_KscanEvent kscan_event;
        zmk_ipc_HidKeyboardReport keyboard;
        zmk_ipc_HidConsumerReport consumer;
        zmk_ipc_HidMouseReport mouse;
    } payload;
} zmk_ipc_ZmkEvent;

/* Used as a placeholder return type where no response data is needed. */
typedef struct _zmk_ipc_Empty {
    char dummy_field;
} zmk_ipc_Empty;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _zmk_ipc_TransportType_MIN zmk_ipc_TransportType_TRANSPORT_UNSPECIFIED
#define _zmk_ipc_TransportType_MAX zmk_ipc_TransportType_TRANSPORT_BLE
#define _zmk_ipc_TransportType_ARRAYSIZE ((zmk_ipc_TransportType)(zmk_ipc_TransportType_TRANSPORT_BLE+1))

#define _zmk_ipc_KeyEvent_Action_MIN zmk_ipc_KeyEvent_Action_ACTION_UNSPECIFIED
#define _zmk_ipc_KeyEvent_Action_MAX zmk_ipc_KeyEvent_Action_RELEASE
#define _zmk_ipc_KeyEvent_Action_ARRAYSIZE ((zmk_ipc_KeyEvent_Action)(zmk_ipc_KeyEvent_Action_RELEASE+1))

#define zmk_ipc_Endpoint_transport_ENUMTYPE zmk_ipc_TransportType


#define zmk_ipc_KeyEvent_action_ENUMTYPE zmk_ipc_KeyEvent_Action









/* Initializer values for message structs */
#define zmk_ipc_Endpoint_init_default            {_zmk_ipc_TransportType_MIN, 0}
#define zmk_ipc_KeyPosition_init_default         {0, 0}
#define zmk_ipc_KeyEvent_init_default            {_zmk_ipc_KeyEvent_Action_MIN, 0, {zmk_ipc_KeyPosition_init_default}}
#define zmk_ipc_ClientMessage_init_default       {0, {zmk_ipc_KeyEvent_init_default}}
#define zmk_ipc_KscanEvent_init_default          {0, 0, 0, 0}
#define zmk_ipc_HidKeyboardReport_init_default   {false, zmk_ipc_Endpoint_init_default, 0, {0, {0}}}
#define zmk_ipc_HidConsumerReport_init_default   {false, zmk_ipc_Endpoint_init_default, {0, {0}}}
#define zmk_ipc_HidMouseReport_init_default      {false, zmk_ipc_Endpoint_init_default, 0, 0, 0, 0, 0}
#define zmk_ipc_ZmkEvent_init_default            {0, {zmk_ipc_KscanEvent_init_default}}
#define zmk_ipc_Empty_init_default               {0}
#define zmk_ipc_Endpoint_init_zero               {_zmk_ipc_TransportType_MIN, 0}
#define zmk_ipc_KeyPosition_init_zero            {0, 0}
#define zmk_ipc_KeyEvent_init_zero               {_zmk_ipc_KeyEvent_Action_MIN, 0, {zmk_ipc_KeyPosition_init_zero}}
#define zmk_ipc_ClientMessage_init_zero          {0, {zmk_ipc_KeyEvent_init_zero}}
#define zmk_ipc_KscanEvent_init_zero             {0, 0, 0, 0}
#define zmk_ipc_HidKeyboardReport_init_zero      {false, zmk_ipc_Endpoint_init_zero, 0, {0, {0}}}
#define zmk_ipc_HidConsumerReport_init_zero      {false, zmk_ipc_Endpoint_init_zero, {0, {0}}}
#define zmk_ipc_HidMouseReport_init_zero         {false, zmk_ipc_Endpoint_init_zero, 0, 0, 0, 0, 0}
#define zmk_ipc_ZmkEvent_init_zero               {0, {zmk_ipc_KscanEvent_init_zero}}
#define zmk_ipc_Empty_init_zero                  {0}

/* Field tags (for use in manual encoding/decoding) */
#define zmk_ipc_Endpoint_transport_tag           1
#define zmk_ipc_Endpoint_ble_profile_idx_tag     2
#define zmk_ipc_KeyPosition_row_tag              1
#define zmk_ipc_KeyPosition_col_tag              2
#define zmk_ipc_KeyEvent_action_tag              1
#define zmk_ipc_KeyEvent_key_pos_tag             2
#define zmk_ipc_KeyEvent_position_tag            3
#define zmk_ipc_ClientMessage_key_event_tag      1
#define zmk_ipc_KscanEvent_source_tag            1
#define zmk_ipc_KscanEvent_position_tag          2
#define zmk_ipc_KscanEvent_pressed_tag           3
#define zmk_ipc_KscanEvent_timestamp_tag         4
#define zmk_ipc_HidKeyboardReport_endpoint_tag   1
#define zmk_ipc_HidKeyboardReport_modifiers_tag  2
#define zmk_ipc_HidKeyboardReport_keys_tag       3
#define zmk_ipc_HidConsumerReport_endpoint_tag   1
#define zmk_ipc_HidConsumerReport_keys_tag       2
#define zmk_ipc_HidMouseReport_endpoint_tag      1
#define zmk_ipc_HidMouseReport_buttons_tag       2
#define zmk_ipc_HidMouseReport_dx_tag            3
#define zmk_ipc_HidMouseReport_dy_tag            4
#define zmk_ipc_HidMouseReport_scroll_x_tag      5
#define zmk_ipc_HidMouseReport_scroll_y_tag      6
#define zmk_ipc_ZmkEvent_kscan_event_tag         1
#define zmk_ipc_ZmkEvent_keyboard_tag            2
#define zmk_ipc_ZmkEvent_consumer_tag            3
#define zmk_ipc_ZmkEvent_mouse_tag               4

/* Struct field encoding specification for nanopb */
#define zmk_ipc_Endpoint_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    transport,         1) \
X(a, STATIC,   SINGULAR, UINT32,   ble_profile_idx,   2)
#define zmk_ipc_Endpoint_CALLBACK NULL
#define zmk_ipc_Endpoint_DEFAULT NULL

#define zmk_ipc_KeyPosition_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   row,               1) \
X(a, STATIC,   SINGULAR, UINT32,   col,               2)
#define zmk_ipc_KeyPosition_CALLBACK NULL
#define zmk_ipc_KeyPosition_DEFAULT NULL

#define zmk_ipc_KeyEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    action,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (address,key_pos,address.key_pos),   2) \
X(a, STATIC,   ONEOF,    UINT32,   (address,position,address.position),   3)
#define zmk_ipc_KeyEvent_CALLBACK NULL
#define zmk_ipc_KeyEvent_DEFAULT NULL
#define zmk_ipc_KeyEvent_address_key_pos_MSGTYPE zmk_ipc_KeyPosition

#define zmk_ipc_ClientMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,key_event,payload.key_event),   1)
#define zmk_ipc_ClientMessage_CALLBACK NULL
#define zmk_ipc_ClientMessage_DEFAULT NULL
#define zmk_ipc_ClientMessage_payload_key_event_MSGTYPE zmk_ipc_KeyEvent

#define zmk_ipc_KscanEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   source,            1) \
X(a, STATIC,   SINGULAR, UINT32,   position,          2) \
X(a, STATIC,   SINGULAR, BOOL,     pressed,           3) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,         4)
#define zmk_ipc_KscanEvent_CALLBACK NULL
#define zmk_ipc_KscanEvent_DEFAULT NULL

#define zmk_ipc_HidKeyboardReport_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  endpoint,          1) \
X(a, STATIC,   SINGULAR, UINT32,   modifiers,         2) \
X(a, STATIC,   SINGULAR, BYTES,    keys,              3)
#define zmk_ipc_HidKeyboardReport_CALLBACK NULL
#define zmk_ipc_HidKeyboardReport_DEFAULT NULL
#define zmk_ipc_HidKeyboardReport_endpoint_MSGTYPE zmk_ipc_Endpoint

#define zmk_ipc_HidConsumerReport_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  endpoint,          1) \
X(a, STATIC,   SINGULAR, BYTES,    keys,              2)
#define zmk_ipc_HidConsumerReport_CALLBACK NULL
#define zmk_ipc_HidConsumerReport_DEFAULT NULL
#define zmk_ipc_HidConsumerReport_endpoint_MSGTYPE zmk_ipc_Endpoint

#define zmk_ipc_HidMouseReport_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  endpoint,          1) \
X(a, STATIC,   SINGULAR, UINT32,   buttons,           2) \
X(a, STATIC,   SINGULAR, SINT32,   dx,                3) \
X(a, STATIC,   SINGULAR, SINT32,   dy,                4) \
X(a, STATIC,   SINGULAR, SINT32,   scroll_x,          5) \
X(a, STATIC,   SINGULAR, SINT32,   scroll_y,          6)
#define zmk_ipc_HidMouseReport_CALLBACK NULL
#define zmk_ipc_HidMouseReport_DEFAULT NULL
#define zmk_ipc_HidMouseReport_endpoint_MSGTYPE zmk_ipc_Endpoint

#define zmk_ipc_ZmkEvent_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,kscan_event,payload.kscan_event),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,keyboard,payload.keyboard),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,consumer,payload.consumer),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,mouse,payload.mouse),   4)
#define zmk_ipc_ZmkEvent_CALLBACK NULL
#define zmk_ipc_ZmkEvent_DEFAULT NULL
#define zmk_ipc_ZmkEvent_payload_kscan_event_MSGTYPE zmk_ipc_KscanEvent
#define zmk_ipc_ZmkEvent_payload_keyboard_MSGTYPE zmk_ipc_HidKeyboardReport
#define zmk_ipc_ZmkEvent_payload_consumer_MSGTYPE zmk_ipc_HidConsumerReport
#define zmk_ipc_ZmkEvent_payload_mouse_MSGTYPE zmk_ipc_HidMouseReport

#define zmk_ipc_Empty_FIELDLIST(X, a) \

#define zmk_ipc_Empty_CALLBACK NULL
#define zmk_ipc_Empty_DEFAULT NULL

extern const pb_msgdesc_t zmk_ipc_Endpoint_msg;
extern const pb_msgdesc_t zmk_ipc_KeyPosition_msg;
extern const pb_msgdesc_t zmk_ipc_KeyEvent_msg;
extern const pb_msgdesc_t zmk_ipc_ClientMessage_msg;
extern const pb_msgdesc_t zmk_ipc_KscanEvent_msg;
extern const pb_msgdesc_t zmk_ipc_HidKeyboardReport_msg;
extern const pb_msgdesc_t zmk_ipc_HidConsumerReport_msg;
extern const pb_msgdesc_t zmk_ipc_HidMouseReport_msg;
extern const pb_msgdesc_t zmk_ipc_ZmkEvent_msg;
extern const pb_msgdesc_t zmk_ipc_Empty_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define zmk_ipc_Endpoint_fields &zmk_ipc_Endpoint_msg
#define zmk_ipc_KeyPosition_fields &zmk_ipc_KeyPosition_msg
#define zmk_ipc_KeyEvent_fields &zmk_ipc_KeyEvent_msg
#define zmk_ipc_ClientMessage_fields &zmk_ipc_ClientMessage_msg
#define zmk_ipc_KscanEvent_fields &zmk_ipc_KscanEvent_msg
#define zmk_ipc_HidKeyboardReport_fields &zmk_ipc_HidKeyboardReport_msg
#define zmk_ipc_HidConsumerReport_fields &zmk_ipc_HidConsumerReport_msg
#define zmk_ipc_HidMouseReport_fields &zmk_ipc_HidMouseReport_msg
#define zmk_ipc_ZmkEvent_fields &zmk_ipc_ZmkEvent_msg
#define zmk_ipc_Empty_fields &zmk_ipc_Empty_msg

/* Maximum encoded size of messages (where known) */
#define ZMK_IPC_ZMK_IPC_PB_H_MAX_SIZE            zmk_ipc_ZmkEvent_size
#define zmk_ipc_ClientMessage_size               18
#define zmk_ipc_Empty_size                       0
#define zmk_ipc_Endpoint_size                    8
#define zmk_ipc_HidConsumerReport_size           28
#define zmk_ipc_HidKeyboardReport_size           50
#define zmk_ipc_HidMouseReport_size              40
#define zmk_ipc_KeyEvent_size                    16
#define zmk_ipc_KeyPosition_size                 12
#define zmk_ipc_KscanEvent_size                  25
#define zmk_ipc_ZmkEvent_size                    52

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
