/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "zmk_ipc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(zmk_ipc_Endpoint, zmk_ipc_Endpoint, AUTO)


PB_BIND(zmk_ipc_KeyPosition, zmk_ipc_KeyPosition, AUTO)


PB_BIND(zmk_ipc_KeyEvent, zmk_ipc_KeyEvent, AUTO)


PB_BIND(zmk_ipc_ClientMessage, zmk_ipc_ClientMessage, AUTO)


PB_BIND(zmk_ipc_KscanEvent, zmk_ipc_KscanEvent, AUTO)


PB_BIND(zmk_ipc_HidKeyboardReport, zmk_ipc_HidKeyboardReport, AUTO)


PB_BIND(zmk_ipc_HidConsumerReport, zmk_ipc_HidConsumerReport, AUTO)


PB_BIND(zmk_ipc_HidMouseReport, zmk_ipc_HidMouseReport, AUTO)


PB_BIND(zmk_ipc_ZmkEvent, zmk_ipc_ZmkEvent, AUTO)


PB_BIND(zmk_ipc_Empty, zmk_ipc_Empty, AUTO)







